src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
  path('', include('yfcases.urls')),
  path('admin/', admin.site.urls),
  path('users/', include('users.urls')),
  path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yfcases/urls.py
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from .views import *

app_name='yfcase'

urlpatterns = [
  # 登入
  path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
  #忘記密碼
  path('password-reset/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password_reset'),
  path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
  path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
  path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),

  # path('',YfcaseListView.as_view(),name="home" ),
  path('',yfcase_list,name="home" ),
  path('all/',yfcase_list_all,name="home_all" ),
  path('all_include_close/',yfcase_list_all_include_close,name="home_all_include_close" ),
  path('yfcase/<int:pk>/',YfcaseDetailView.as_view(),name="yfcase_detail" ),
  path('yfcase/create/',YfcaseCreateView.as_view(),name="yfcase_create" ),
  path('yfcase/<int:pk>/update/',YfcaseUpdateView.as_view(),name="yfcase_update"),
  path('yfcase/<int:pk>/delete/',YfcaseDeleteView.as_view(),name="yfcase_delete"),
  # Land
  path('yfcase/<int:yfcase_id>/land/create/',land_create,name="land_create" ),
  path('yfcase/<int:yfcase_id>/land/update/<int:id>/',land_update,name="land_update" ),
  path('yfcase/<int:yfcase_id>/land/delete/<int:id>/',land_delete,name="land_delete" ),
  # Build
  path('yfcase/<int:yfcase_id>/build/create/',build_create,name="build_create" ),
  path('yfcase/<int:yfcase_id>/build/update/<int:id>/',build_update,name="build_update" ),
  path('yfcase/<int:yfcase_id>/build/delete/<int:id>/',build_delete,name="build_delete" ),
  # Aucion
  path('yfcase/<int:yfcase_id>/auction/create/',auction_create,name="auction_create" ),
  path('yfcase/<int:yfcase_id>/auction/update/<int:id>/',auction_update,name="auction_update" ),
  # Survey
  path('yfcase/<int:yfcase_id>/survey/create/',survey_create,name="survey_create" ),
  path('yfcase/<int:yfcase_id>/survey/update/<int:id>/',survey_update,name="survey_update" ),
  # ObjectBuild
  path('yfcase/<int:yfcase_id>/objectbuild/create/',objectbuild_create,name="objectbuild_create" ),
  path('yfcase/<int:yfcase_id>/objectbuild/update/<int:id>/',objectbuild_update,name="objectbuild_update" ),
  path('yfcase/<int:yfcase_id>/objectbuild/delete/<int:id>/',objectbuild_delete,name="objectbuild_delete" ),
  # ScoreA
  path('yfcase/<int:yfcase_id>/scorea/update/<int:id>/',score_a_adj,name="score_a_update" ),
  path('yfcase/<int:yfcase_id>/scorea/delete/<int:id>/',score_a_clean,name="score_a_delete" ),
  # ScoreB
  path('yfcase/<int:yfcase_id>/scoreb/update/<int:id>/',score_b_adj,name="score_b_update" ),
  path('yfcase/<int:yfcase_id>/scoreb/delete/<int:id>/',score_b_clean,name="score_b_delete" ),
  # ScoreC
  path('yfcase/<int:yfcase_id>/scorec/update/<int:id>/',score_c_adj,name="score_c_update" ),
  path('yfcase/<int:yfcase_id>/scorec/delete/<int:id>/',score_c_clean,name="score_c_delete" ),
  # FinalDecision
  path('yfcase/<int:yfcase_id>/finaldecision/create/',finaldecision_create,name="finaldecision_create" ),
  path('yfcase/<int:yfcase_id>/finaldecision/update/<int:id>/',finaldecision_update,name="finaldecision_update" ),
  path('yfcase/<int:yfcase_id>/finaldecision/delete/<int:id>/',finaldecision_delete,name="finaldecision_delete" ),
  # SubSigntrueA
  path('yfcase/<int:yfcase_id>/subsignturea/update/<int:id>/',subsignture_a_update,name="subsignture_a_update" ),
  path('yfcase/<int:yfcase_id>/subsignturea/delete/<int:id>/',subsignture_a_delete,name="subsignture_a_delete" ),
  # SubSigntrueB
  path('yfcase/<int:yfcase_id>/subsigntureb/update/<int:id>/',subsignture_b_update,name="subsignture_b_update" ),
  path('yfcase/<int:yfcase_id>/subsigntureb/delete/<int:id>/',subsignture_b_delete,name="subsignture_b_delete" ),
  # Result
  path('yfcase/<int:yfcase_id>/result/create/',result_create,name="result_create" ),
  path('yfcase/<int:yfcase_id>/result/update/<int:id>/',result_update,name="result_update" ),

  path('ajax/load-townships/', load_townships, name='ajax_load_townships'),
  
  # 匯出資料
  path('export-excel/',export_yfcase,name='export'),


]

templates/yfcase/afterwinner/Complaint_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block style %}
  <style type="text/css">
    .help-block{
      color:red;
    }
    .coowner__table { border-collapse: collapse;}
    .coowner__table th { border: 1px solid black; background-color: yellow;padding: 0px;text-align: center;}
    .coowner__table .coowner__td{ border: 1px solid black;text-align: center; }

    .coownerheir__table  { border-collapse: collapse;width: 100%;}
    .coownerheir__table th {border: 1px solid black; background-color: lightgreen;padding: 0px;text-align: center;font-size: 10pt;}
    .coownerheir__table td { border: 1px solid black; font-size: 10pt;text-align: center;}
    .coowner__table td.text-left { text-align: left; }

    .btn__icon__create { background-color: MediumBlue; border:2px solid darkgrey; border-radius: 5px; padding:2px 7px; font-weight: 500; color:white; text-decoration:none; }
    .btn__icon__update { background-color: DarkGreen; border:2px solid darkgrey; border-radius: 5px; padding:2px 7px; font-weight: 500; color:white; text-decoration:none; }
    .btn__icon__delete { background-color: DarkRed; border:2px solid darkgrey; border-radius: 5px; padding:2px 7px; font-weight: 500; color:white; text-decoration:none; }
  </style>
{% endblock style %}

{% block content %}
<div class="col-md p-2 bg-light">
  <!-- 程式主題的部份 -->
  <form action="{% url 'yfcase:complaint_edit' yfcase.id %}" method="post" id="Complaint_edit_form" data-townships-url="{% url 'yfcase:ajax_load_townships' %}">{% csrf_token %}
    <!-- header -->
    <h1>{{title}}</h1>
    
    <div class="col mb-3 text-center fs-2 bg-warning rounded-pill">
      訴訟狀 - 案號：{{ yfcase.yfcaseCaseNumber }}
    </div>

    <!-- 起訴狀填寫日期、訴訟狀委託人、土地公告現值、房屋課稅現值 -->
    <div class="row">
      <!-- 訴訟狀委託人 -->
      <div class="col-md-3 mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintLitigationAgent.label }}
          </label>
          {{ form.yfcaseComplaintLitigationAgent|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintLitigationAgent.error }}
          </span>
        </div>
      </div>
      <!-- 起訴狀填寫日期 -->
      <div class="col-md-3 mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintComplaintDate.label }}
          </label>
          {{ form.yfcaseComplaintComplaintDate|add_class:'form-control border border-dark datepicker fieldcolor' }}
          <span class="help-block">
            {{ form.yfcaseComplaintComplaintDate.error }}
          </span>
        </div>
      </div>
      <!-- 土地公告現值 -->
      <div class="col-md-3 mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintPresentValueOfLandAnnouncement.label }}
          </label>
          {{ form.yfcaseComplaintPresentValueOfLandAnnouncement|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintPresentValueOfLandAnnouncement.error }}
          </span>
        </div>
      </div>
      <!-- 房屋課稅現值 -->
      <div class="col-md-3 mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintPresentValueOfHouseTax.label }}
          </label>
          {{ form.yfcaseComplaintPresentValueOfHouseTax|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintPresentValueOfHouseTax.error }}
          </span>
        </div>
      </div>
    </div>

    <!-- 裁判費、分割未果日期、土地面寬、土地深度 -->
    <div class="row">
      <!-- 裁判費 -->
      <div class="col-md-3 mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintRefereeFee.label }}
          </label>
          {{ form.yfcaseComplaintRefereeFee|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintRefereeFee.error }}
          </span>
        </div>
      </div>
      <!-- 分割未果日期 -->
      <div class="col-md-3 mb-3">
         <div class="form-group">
          <label>
            {{ form.yfcaseComplaintUnsuccessfulDate.label }}
          </label>
          {{ form.yfcaseComplaintUnsuccessfulDate|add_class:'form-control border border-dark datepicker fieldcolor' }}
          <span class="help-block">
            {{ form.yfcaseComplaintUnsuccessfulDate.error }}
          </span>
        </div>
      </div>
      <!-- 土地面寬 -->
      <div class="col-md-3 mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintLandWidth.label }}
          </label>
          {{ form.yfcaseComplaintLandWidth|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintLandWidth.error }}
          </span>
        </div>
      </div>
      <!-- 土地深度 -->
      <div class="col-md-3 mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintLandDepth.label }}
          </label>
          {{ form.yfcaseComplaintLandDepth|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintLandDepth.error }}
          </span>
        </div>
      </div>
    </div>

    <!-- 證物1 -->
    <div class="row">
      <div class="col-md mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintExhibit1.label }}
          </label>
          {{ form.yfcaseComplaintExhibit1|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintExhibit1.error }}
          </span>
        </div>
      </div>
    </div>
    <!-- 證物2 -->
    <div class="row">
      <div class="col-md mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintExhibit2.label }}
          </label>
          {{ form.yfcaseComplaintExhibit2|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintExhibit2.error }}
          </span>
        </div>
      </div>
    </div>
    <!-- 證物3 -->
    <div class="row">
      <div class="col-md mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintExhibit3.label }}
          </label>
          {{ form.yfcaseComplaintExhibit3|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintExhibit3.error }}
          </span>
        </div>
      </div>
    </div>
    <!-- 證物4 -->
    <div class="row">
      <div class="col-md mb-3">
        <div class="form-group">
          <label>
            {{ form.yfcaseComplaintExhibit4.label }}
          </label>
          {{ form.yfcaseComplaintExhibit4|add_class:'form-control border border-dark' }}
          <span class="help-block">
            {{ form.yfcaseComplaintExhibit4.error }}
          </span>
        </div>
      </div>
    </div>

    {{ complaint_clent_id|json_script:"complaint_clent_id" }}

    <div class="row">
      <div class="col-md-6 mb-3">
        <a href="{% url 'yfcase:home' %}" class="btn btn-secondary form-control" >返回</a>
      </div>
      <div class="col-md-6 mb-3">
        <input class="btn btn-primary form-control" type="submit" value="建立" />
      </div>
    </div>
        
  </form>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
  /* global $ */
  $(document).ready(function(){
    const complaint_clent_id = JSON.parse(document.getElementById('complaint_clent_id').textContent);
    document.getElementById("id_yfcaseComplaintLitigationAgent").value = complaint_clent_id; 
    // 此為欄位驗証的JS
    $('#Complaint_edit_form').bootstrapValidator({
      // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
      feedbackIcons: {
          valid: 'glyphicon glyphicon-ok',
          invalid: 'glyphicon glyphicon-remove',
          validating: 'glyphicon glyphicon-refresh'
      },
      fields: {
        yfcaseComplaintLitigationAgent: {
          validators: {
            notEmpty: {
              message: '此一欄位不得為空'
            }
          }
        },
      }
    });

  });

  $(function() {
    $(".datepicker").datepicker({
      dateFormat: "yy-mm-dd"
    });
  });


</script>
{% endblock content %}

templates/yfcase/afterwinner/Letter_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block style %}
  <style type="text/css">
    .help-block{
      color:red;
    }
  </style>
{% endblock style %}

{% block content %}
<div class="col-md p-2 bg-light">
  <!-- 程式主題的部份 -->
  <form action="{% url 'yfcase:letter_edit' yfcase.id %}" method="post" id="letter_edit_form" data-townships-url="{% url 'yfcase:ajax_load_townships' %}" >{% csrf_token %}
    <!-- header -->
    <h1>{{title}}</h1>
    <div class="col mb-3 text-center fs-2 bg-warning rounded-pill">
      存證信函 - 案號：{{ yfcase.yfcaseCaseNumber }}
    </div>
      
    <div class="row">
      <div class="col mb-3">
        <div class="form-group">
          <label for="{{ form.yfcaseLetterAgent.id_for_label }}">{{ form.yfcaseLetterAgent.label }}</label>
          {{ form.yfcaseLetterAgent|add_class:'form-control border border-dark' }}
          <span class="help-block">{{ form.yfcaseLetterAgent.error }}</span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col mb-3">
        <div class="form-group">
          <label for="{{ form.yfcaseLetterSender.id_for_label }}">{{ form.yfcaseLetterSender.label }}</label>
          {{ form.yfcaseLetterSender|add_class:'form-control border border-dark' }}
          <span class="help-block">{{ form.yfcaseLetterSender.error }}</span>
        </div>
      </div>
    </div>
      
    {{ letter_clent_id|json_script:"letter_clent_id" }}

    <!-- footer -->
    <div class="row">
      <div class="col-md-6 mb-3">
        <button type="button" class="btn btn-secondary col" data-dismiss="modal">返回</button>
      </div>
      <div class="col-md-6 mb-3">
        <input class="btn btn-primary col-md-3" type="submit" value="建立" />
      </div>
    </div>
    
  </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
  $(document).ready(function(){
    const letter_clent_id = JSON.parse(document.getElementById('letter_clent_id').textContent);
    document.getElementById("id_yfcaseLetterAgent").value = letter_clent_id; 
    // 此為欄位驗証的JS
    $('#letter_edit_form').bootstrapValidator({
      // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
      feedbackIcons: {
        valid: 'glyphicon glyphicon-ok',
        invalid: 'glyphicon glyphicon-remove',
        validating: 'glyphicon glyphicon-refresh'
      },
      fields: {
      }
    });

  });

  $(function() {
    $(".datepicker").datepicker({
      dateFormat: "yy-mm-dd"
    });
  });

</script>
{% endblock %}

templates/yfcase/afterwinner/Realestateregistration_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block style %}
  <style type="text/css">
    .help-block{
      color:red;
    }
  </style>
{% endblock style %}

{% block content %}

<div class="col-md p-2 bg-light">
  <!-- 程式主題的部份 -->
  <form action="{% url 'yfcase:realestateregistration_edit' yfcase.id %}" method="post" id="editRealestateregistrationModal" data-townships-url="{% url 'yfcase:ajax_load_townships' %}">{% csrf_token %}

  <!-- header -->
  <h1>{{title}}</h1>
  
  <div class="col mb-3 text-center fs-2 bg-warning rounded-pill">
    不動產登記 - 案號：{{ yfcase.yfcaseCaseNumber }}
  </div>
  
  <!--不動產登記代理人-->
  <div class="col mb-3">
    <div class="form-group">
      <label>{{ form.yfcaseRealEstateRegistrationRegisteredAgent.label }}</label>
      {{ form.yfcaseRealEstateRegistrationRegisteredAgent|add_class:'form-control border border-dark' }}
      <span class="help-block">{{ form.yfcaseRealEstateRegistrationRegisteredAgent.error }}</span>
    </div>
  </div>
  <!--原因發生日期-->
  <div class="col mb-3">
    <div class="form-group">
      <label>{{ form.yfcaseRealEstateRegistrationDateOfCause.label }}</label>
      {{ form.yfcaseRealEstateRegistrationDateOfCause|add_class:'form-control border border-dark fieldcolor datepicker' }}
      <span class="help-block">{{ form.yfcaseRealEstateRegistrationDateOfCause.error }}</span>
    </div>
  </div>
  <!--登記原因-->
  <div class="col mb-3">
    <div class="form-group">
      <label>{{ form.yfcaseRealEstateRegistrationReasonForRegistration.label }}</label>
      {{ form.yfcaseRealEstateRegistrationReasonForRegistration|add_class:'form-control border border-dark' }}
      <span class="help-block">{{ form.yfcaseRealEstateRegistrationReasonForRegistration.error }}</span>
    </div>
  </div>
  <!--登記備註-->
  <div class="col mb-3">
    <div class="form-group">
      <label>{{ form.yfcaseRealEstateRegistrationRegistrationNote.label }}</label>
      {{ form.yfcaseRealEstateRegistrationRegistrationNote|add_class:'form-control border border-dark' }}
      <span class="help-block">{{ form.yfcaseRealEstateRegistrationRegistrationNote.error }}</span>
    </div>
  </div>
  <!--跨所申請-->
  <div class="col mb-3">
    <div class="form-group">
      {% render_field form.yfcaseApplyAcrossInstitutions|attr:"multiple:multiple"|attr:"data-plugin-multiselect" %} <span style="color:red;">跨所申請</span>
      <span class="help-block">{{ form.yfcaseApplyAcrossInstitutions.error }}</span>
    </div>
  </div>
  <!--受理機關-鄉鎮-->
  <div class="col mb-3">
    <div class="form-group">
      <label>{{ form.yfcaseAcceptingAuthorityTownship.label }}</label>
      {{ form.yfcaseAcceptingAuthorityTownship|add_class:'form-control border border-dark' }}
      <span class="help-block">{{ form.yfcaseAcceptingAuthorityTownship.error }}</span>
    </div>
  </div>

  {{ realestateregistration_user_id|json_script:"realestateregistration_clent_id" }}

  <!-- footer -->
  <div class="row">
    <div class="col-md-6 mb-3">
      <a href="{% url 'yfcase:home' %}" class="btn btn-secondary form-control">返回</a>
    </div>
    <div class="col-md-6 mb-3">
      <input class="btn btn-primary form-control" type="submit" value="建立" />
    </div>
  </div>

</form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
  /* global $ */
  $(document).ready(function(){
    const realestateregistration_clent_id = JSON.parse(document.getElementById('realestateregistration_clent_id').textContent);
    document.getElementById("id_yfcaseRealEstateRegistrationRegisteredAgent").value = realestateregistration_clent_id;
    // 此為欄位驗証的JS
    $('#editRealestateregistrationModal').bootstrapValidator({
      // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
      feedbackIcons: {
          valid: 'glyphicon glyphicon-ok',
          invalid: 'glyphicon glyphicon-remove',
          validating: 'glyphicon glyphicon-refresh'
      },
      fields: {
        yfcaseRealEstateRegistrationRegisteredAgent: {
          validators: {
            notEmpty: {
              message: '此一欄位不得為空'
            }
          }
        }  
      }
    });

  });
  $(function() {
    $(".datepicker").datepicker({
      dateFormat: "yy-mm-dd"
    });
  });

</script>
{% endblock content %}