src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
  path('', include('yfcases.urls')),
  path('admin/', admin.site.urls),
  path('users/', include('users.urls')),
  path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yfcases/urls.py
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from .views import *

app_name='yfcase'

urlpatterns = [
  # 登入
  path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
  #忘記密碼
  path('password-reset/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password_reset'),
  path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
  path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
  path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),

  # path('',YfcaseListView.as_view(),name="home" ),
  path('',yfcase_list,name="home" ),
  path('all/',yfcase_list_all,name="home_all" ),
  path('all_include_close/',yfcase_list_all_include_close,name="home_all_include_close" ),
  path('yfcase/<int:pk>/',YfcaseDetailView.as_view(),name="yfcase_detail" ),
  path('yfcase/create/',YfcaseCreateView.as_view(),name="yfcase_create" ),
  path('yfcase/<int:pk>/update/',YfcaseUpdateView.as_view(),name="yfcase_update"),
  path('yfcase/<int:pk>/delete/',YfcaseDeleteView.as_view(),name="yfcase_delete"),
  # Land
  path('yfcase/<int:yfcase_id>/land/create/',land_create,name="land_create" ),
  path('yfcase/<int:yfcase_id>/land/update/<int:id>/',land_update,name="land_update" ),
  path('yfcase/<int:yfcase_id>/land/delete/<int:id>/',land_delete,name="land_delete" ),
  # Build
  path('yfcase/<int:yfcase_id>/build/create/',build_create,name="build_create" ),
  path('yfcase/<int:yfcase_id>/build/update/<int:id>/',build_update,name="build_update" ),
  path('yfcase/<int:yfcase_id>/build/delete/<int:id>/',build_delete,name="build_delete" ),
  # Aucion
  path('yfcase/<int:yfcase_id>/auction/create/',auction_create,name="auction_create" ),
  path('yfcase/<int:yfcase_id>/auction/update/<int:id>/',auction_update,name="auction_update" ),
  # Survey
  path('yfcase/<int:yfcase_id>/survey/create/',survey_create,name="survey_create" ),
  path('yfcase/<int:yfcase_id>/survey/update/<int:id>/',survey_update,name="survey_update" ),
  # ObjectBuild
  path('yfcase/<int:yfcase_id>/objectbuild/create/',objectbuild_create,name="objectbuild_create" ),
  path('yfcase/<int:yfcase_id>/objectbuild/update/<int:id>/',objectbuild_update,name="objectbuild_update" ),
  path('yfcase/<int:yfcase_id>/objectbuild/delete/<int:id>/',objectbuild_delete,name="objectbuild_delete" ),
  # ScoreA
  path('yfcase/<int:yfcase_id>/scorea/update/<int:id>/',score_a_adj,name="score_a_update" ),
  path('yfcase/<int:yfcase_id>/scorea/delete/<int:id>/',score_a_clean,name="score_a_delete" ),
  # ScoreB
  path('yfcase/<int:yfcase_id>/scoreb/update/<int:id>/',score_b_adj,name="score_b_update" ),
  path('yfcase/<int:yfcase_id>/scoreb/delete/<int:id>/',score_b_clean,name="score_b_delete" ),
  # ScoreC
  path('yfcase/<int:yfcase_id>/scorec/update/<int:id>/',score_c_adj,name="score_c_update" ),
  path('yfcase/<int:yfcase_id>/scorec/delete/<int:id>/',score_c_clean,name="score_c_delete" ),
  # FinalDecision
  path('yfcase/<int:yfcase_id>/finaldecision/create/',finaldecision_create,name="finaldecision_create" ),
  path('yfcase/<int:yfcase_id>/finaldecision/update/<int:id>/',finaldecision_update,name="finaldecision_update" ),
  path('yfcase/<int:yfcase_id>/finaldecision/delete/<int:id>/',finaldecision_delete,name="finaldecision_delete" ),
  # SubSigntrueA
  path('yfcase/<int:yfcase_id>/subsignturea/update/<int:id>/',subsignture_a_update,name="subsignture_a_update" ),
  path('yfcase/<int:yfcase_id>/subsignturea/delete/<int:id>/',subsignture_a_delete,name="subsignture_a_delete" ),
  # SubSigntrueB
  path('yfcase/<int:yfcase_id>/subsigntureb/update/<int:id>/',subsignture_b_update,name="subsignture_b_update" ),
  path('yfcase/<int:yfcase_id>/subsigntureb/delete/<int:id>/',subsignture_b_delete,name="subsignture_b_delete" ),
  # Result
  path('yfcase/<int:yfcase_id>/result/create/',result_create,name="result_create" ),
  path('yfcase/<int:yfcase_id>/result/update/<int:id>/',result_update,name="result_update" ),

  path('ajax/load-townships/', load_townships, name='ajax_load_townships'),
  
  # 匯出資料
  path('export-excel/',export_yfcase,name='export'),


]

templates/yfcase/formset.html
{% load crispy_forms_tags %}
{% load static %}
<table class="col-md" style="margin-left: 10px;">
{{ formset.management_form|crispy }}

    {% for form in formset.forms %}
      <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
        {% for field in form.visible_fields %}
        <td>
          {# Include the hidden fields in the form #}
          {% if forloop.first %}
            {% for hidden in form.hidden_fields %}
              {{ hidden }}
            {% endfor %}
          {% endif %}
          {{ field.errors.as_ul }}
          {{ field|as_crispy_field }}
        </td>
        {% endfor %}
      </tr>
    {% endfor %}

</table>
<br>

<script src='{% static "js/jquery.formset.js" %}'></script>
<script type="text/javascript">
  /* global $ */
  $('.formset_row-{{ formset.prefix }}').formset({
    addText: '新增(編輯)共有人',
    deleteText: 'remove',
    prefix: '{{ formset.prefix }}',
  });
</script>

templates/yfcase/township_dropdown_list_options.html
<option value="">---------</option>
{% for township in townships %}
<option value="{{ township.pk }}">{{ township.name }}</option>
{% endfor %}

templates/yfcase/yfcase_delete.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block style %}

{% endblock style %}

{% block content %}
  <form action="{% url 'yfcase:yfcase_delete' yfcase.id %}" method="post">{% csrf_token %}
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- header -->
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">刪除</h5>
        </div>
        
        <!-- body -->
        <div class="modal-body">
         <p>你確定要刪除 "{{yfcase.yfcaseCaseNumber}}" ?</p>
        </div>

        <!-- footer -->
        <div class="modal-footer">
          <a href="{% url 'yfcase:home' %}" class="btn btn-secondary" >返回</a>
          <input class="btn btn-success col-md-3" type="submit" value="刪除" />
        </div>

      </div>
    </div>
  </form>
{% endblock %}

templates/yfcase/yfcase_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load widget_tweaks %}
{% load humanize %}

{% block style %} 
  <style>
    * {
      font-family: 'Roboto','Noto Sans TC', sans-serif;
    }
    .yfcase__detail__caption {
      margin-top: 20px;
      font-size: 24pt;
      font-weight: 700;
      text-align: center;
      vertical-align: bottom;
    }
    .yfcase__detail__test {
      display: flex;
      justify-content: space-between;
    }
    .yfcase__detail__subtitle {
      margin-top: 20px;
      direction: flex;
      flex-direction: row;
      text-align: right;
    }
    .yfcase__detail__subtitle > label {
      font-size:16pt;
      font-weight: 700;
    }
    th,td {
      text-align: center;
    }
    th { color:black; }
    td { font-weight: 600; font-size:16px; color:blue; }
    .text-left { text-align: left; }
    .text-right { text-align: right; }
    .link__button { font-size:12pt; }
    .text-red { font-size: 10pt; color: red; font-weight: 700; }
    .text-blue { font-size: 10pt; color: blue; font-weight: 700; }
    .text-green { font-size: 10pt; color: green; font-weight: 700; }
    .text-red-12 { font-size: 12pt; color: red; font-weight: 700; }
    .text-blue-12 { font-size: 12pt; color: blue; font-weight: 700; }
    .text-green-12 { font-size: 12pt; color: green; font-weight: 700; }
    .text-mark { font-size: 10.5pt; background-color: yellow; font-weight: 700; }
    .btn__icon__create { background-color: MediumBlue; border:2px solid darkgrey; border-radius: 5px; padding:2px 7px; font-weight: 500; color:white; text-decoration:none; }
    .btn__icon__update { background-color: DarkGreen; border:2px solid darkgrey; border-radius: 5px; padding:2px 7px; font-weight: 500; color:white; text-decoration:none; }
    .btn__icon__delete { background-color: DarkRed; border:2px solid darkgrey; border-radius: 5px; padding:2px 7px; font-weight: 500; color:white; text-decoration:none; }
    
    .row { margin-bottom: 30px;}
  </style>
{% endblock style %}

{% block content %}


  <!-- 標頭 -->
  <div class="col">
    <div class="yfcase__detail__caption">
      {{object.yfcaseCaseNumber}}評量表
    </div>
  </div>

  
  <div class="col">
    <div class="container col">

      <!--基本資料-->
      <div class="d-flex justify-content-between py-1">
        <div>
          <div>
            <div style="font-size:16pt;font-weight: 700;display: flex;align-items: center; " >
              基本資料
              {% if request.user == object.user or request.user.userRole == 1 %}
                &nbsp;<a class="btn btn-success btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:yfcase_update' object.id %}" role="button">變更</a>
              {% endif %}
            </div> 
          </div>
        </div>
        <div style="font-size:14pt;display: flex;align-items: end;"></div>
      </div>

      <!--基本資料樣版-->
      <div class="row">
        {% include "./partials/baseData.html" %}
      </div>
      
      <!-- 土地資訊 -->
      <div class="d-flex justify-content-between py-1">
        <div>
          <div>
            <div style="font-size:16pt;font-weight: 700;display: flex;align-items: center; " >
              土地資訊
              {% if request.user == object.user or request.user.userRole == 1 %}
                &nbsp;<a class="btn btn-primary btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:land_create' object.id %}" role="button">新增</a>
              {% endif %}
            </div> 
          </div>
        </div>
        <div style="font-size:14pt;display: flex;align-items: end;">
          {% if object.lands.count > 0 %}
            合計：{{ object.get_land_holding_point_area_total|floatformat:"2" }} m<sup>2</sup> 
            ({{ object.get_land_holding_point_area_total|m2toping|floatformat:"2" }} 坪)
          {% endif %}
        </div>
      </div>

      <!--土地樣版-->
      <div class="row">
        {% include "./partials/land.html" %}
      </div>

      <!-- 建物資訊 -->
      <div class="d-flex justify-content-between py-1">
        <div>
          <div>
            <div style="font-size:16pt;font-weight: 700;display: flex;align-items: center; " >
              建物資訊
              {% if request.user == object.user or request.user.userRole == 1 %}
                &nbsp;<a class="btn btn-primary btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:build_create' object.id %}" role="button">新增</a>
              {% endif %}
            </div> 
          </div>
        </div>
        <div style="font-size:14pt;display: flex;align-items: end;">
          {% if object.builds.count > 0 %}
            合計：{{ object.get_build_holding_point_after_group_total|floatformat:"2" }} m<sup>2</sup> 
            ({{ object.get_build_holding_point_after_group_total|m2toping|floatformat:"2" }} 坪)
          {% endif %}
        </div>
      </div>

      <div class="row">
        <!--建物樣版-->
        {% include "./partials/build.html" %}
      </div>

      <!-- 拍賣資訊 -->
      <div class="d-flex justify-content-between py-1">
        <div>
          <div>
            <div style="font-size:16pt;font-weight: 700;display: flex;align-items: center; " >
              拍賣資訊
              {% if request.user == object.user or request.user.userRole == 1 %}
                {% if object.auctions.all %}
                  {% for auction in object.auctions.all %}
                    &nbsp;<a class="btn btn-success btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:auction_update' object.id auction.id %}" role="button">變更</a>
                  {% endfor %}
                {% else %}
                  &nbsp;<a class="btn btn-primary btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:auction_create' object.id %}" role="button">新增</a>
                {% endif %}
              {% endif %}
            </div> 
          </div>
        </div>
        <div style="font-size:14pt;display: flex;align-items: end;"></div>
      </div>

      <div class="row">
        <!--拍賣樣版-->
        {% include "./partials/auction.html" %}
      </div>
  
      <!-- 勘查記錄 -->
      <div class="d-flex justify-content-between py-1">
        <div>
          <div>
            <div style="font-size:16pt;font-weight: 700;display: flex;align-items: center; " >
              勘查記錄
              {% if request.user == object.user or request.user.userRole == 1 %}
                {% if object.surveys.all %}
                  {% for survey in object.surveys.all %}
                    &nbsp;<a class="btn btn-success btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:survey_update' object.id survey.id %}" role="button">變更</a>
                  {% endfor %}
                {% else %}
                  &nbsp;<a class="btn btn-primary btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:survey_create' object.id %}" role="button">新增</a>
                {% endif %}
              {% endif %}

              {% if request.user == object.user or request.user.userRole == 1 %}
              {% endif %}
            </div> 
          </div>
        </div>
        <div style="font-size:14pt;display: flex;align-items: end;"></div>
      </div>
  
      <div class="row">
        <!--實勘樣版-->
        {% include "./partials/survey.html" %}
      </div>
  
      <!-- 參考物件 -->
      <div class="d-flex justify-content-between py-1">
        <div>
          <div>
            <div style="font-size:16pt;font-weight: 700;display: flex;align-items: center; " >
              參考物件
              {% if request.user == object.user or request.user.userRole == 1 %}
                &nbsp;<a class="btn btn-primary btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:objectbuild_create' object.id %}" role="button">新增</a>
              {% endif %}
            </div> 
          </div>
        </div>
        <div style="font-size:14pt;display: flex;align-items: end;">
          {% if object.objectbuilds.count > 0 %}
            時價：{{object.pbk|floatformat:0|intcomma}}元
          {% endif %}
        </div>
      </div>
    
      <div class="row">
        <!-- 參考物件分離樣版 -->
        {% include "./partials/object_building.html" %}
      </div> 

      <!-- 最終判定 -->
      <div class="d-flex justify-content-between py-1">
        <div>
          <div>
            <div style="font-size:16pt;font-weight: 700;display: flex;align-items: center; " >
              最終判定
              {% if request.user == object.user or request.user.userRole == 1 %}
                &nbsp;<a class="btn btn-primary btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:finaldecision_create' object.id %}" role="button">新增</a>
              {% endif %}
            </div> 
          </div>
        </div>
        <div style="font-size:14pt;display: flex;align-items: end;"></div>
      </div>
      
      <div class="row">
        <!-- 最終判定樣版 -->
        {% include "./partials/finalDecision.html" %}
      </div>

      <!-- 執行結果 -->
      <div class="d-flex justify-content-between py-1">
        <div>
          <div>
            <div style="font-size:16pt;font-weight: 700;display: flex;align-items: center; " >
              執行結果
              {% if request.user == object.user or request.user.userRole == 1 %}
                {% if object.results.count == 0 %}
                  &nbsp;<a class="btn btn-primary btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:result_create' object.id %}" role="button">新增</a>
                {% endif %}
              {% endif %}
            </div> 
          </div>
        </div>
        <div style="font-size:14pt;display: flex;align-items: end;"></div>
      </div>
      
      <div class="row">
        <!-- 執行結果樣版 -->
        {% include "./partials/result.html" %}
      </div>

    </div>
  </div>

{% endblock content %}