src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
  path('', include('yfcases.urls')),
  path('admin/', admin.site.urls),
  path('users/', include('users.urls')),
  path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yfcases/urls.py
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from .views import *

app_name='yfcase'

urlpatterns = [
  # 登入
  path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
  #忘記密碼
  path('password-reset/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password_reset'),
  path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
  path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
  path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),

  # path('',YfcaseListView.as_view(),name="home" ),
  path('',yfcase_list,name="home" ),
  path('all/',yfcase_list_all,name="home_all" ),
  path('all_include_close/',yfcase_list_all_include_close,name="home_all_include_close" ),
  path('yfcase/<int:pk>/',YfcaseDetailView.as_view(),name="yfcase_detail" ),
  path('yfcase/create/',YfcaseCreateView.as_view(),name="yfcase_create" ),
  path('yfcase/<int:pk>/update/',YfcaseUpdateView.as_view(),name="yfcase_update"),
  path('yfcase/<int:pk>/delete/',YfcaseDeleteView.as_view(),name="yfcase_delete"),
  # Land
  path('yfcase/<int:yfcase_id>/land/create/',land_create,name="land_create" ),
  path('yfcase/<int:yfcase_id>/land/update/<int:id>/',land_update,name="land_update" ),
  path('yfcase/<int:yfcase_id>/land/delete/<int:id>/',land_delete,name="land_delete" ),
  # Build
  path('yfcase/<int:yfcase_id>/build/create/',build_create,name="build_create" ),
  path('yfcase/<int:yfcase_id>/build/update/<int:id>/',build_update,name="build_update" ),
  path('yfcase/<int:yfcase_id>/build/delete/<int:id>/',build_delete,name="build_delete" ),
  # Aucion
  path('yfcase/<int:yfcase_id>/auction/create/',auction_create,name="auction_create" ),
  path('yfcase/<int:yfcase_id>/auction/update/<int:id>/',auction_update,name="auction_update" ),
  # Survey
  path('yfcase/<int:yfcase_id>/survey/create/',survey_create,name="survey_create" ),
  path('yfcase/<int:yfcase_id>/survey/update/<int:id>/',survey_update,name="survey_update" ),
  # ObjectBuild
  path('yfcase/<int:yfcase_id>/objectbuild/create/',objectbuild_create,name="objectbuild_create" ),
  path('yfcase/<int:yfcase_id>/objectbuild/update/<int:id>/',objectbuild_update,name="objectbuild_update" ),
  path('yfcase/<int:yfcase_id>/objectbuild/delete/<int:id>/',objectbuild_delete,name="objectbuild_delete" ),
  # ScoreA
  path('yfcase/<int:yfcase_id>/scorea/update/<int:id>/',score_a_adj,name="score_a_update" ),
  path('yfcase/<int:yfcase_id>/scorea/delete/<int:id>/',score_a_clean,name="score_a_delete" ),
  # ScoreB
  path('yfcase/<int:yfcase_id>/scoreb/update/<int:id>/',score_b_adj,name="score_b_update" ),
  path('yfcase/<int:yfcase_id>/scoreb/delete/<int:id>/',score_b_clean,name="score_b_delete" ),
  # ScoreC
  path('yfcase/<int:yfcase_id>/scorec/update/<int:id>/',score_c_adj,name="score_c_update" ),
  path('yfcase/<int:yfcase_id>/scorec/delete/<int:id>/',score_c_clean,name="score_c_delete" ),
  # FinalDecision
  path('yfcase/<int:yfcase_id>/finaldecision/create/',finaldecision_create,name="finaldecision_create" ),
  path('yfcase/<int:yfcase_id>/finaldecision/update/<int:id>/',finaldecision_update,name="finaldecision_update" ),
  path('yfcase/<int:yfcase_id>/finaldecision/delete/<int:id>/',finaldecision_delete,name="finaldecision_delete" ),
  # SubSigntrueA
  path('yfcase/<int:yfcase_id>/subsignturea/update/<int:id>/',subsignture_a_update,name="subsignture_a_update" ),
  path('yfcase/<int:yfcase_id>/subsignturea/delete/<int:id>/',subsignture_a_delete,name="subsignture_a_delete" ),
  # SubSigntrueB
  path('yfcase/<int:yfcase_id>/subsigntureb/update/<int:id>/',subsignture_b_update,name="subsignture_b_update" ),
  path('yfcase/<int:yfcase_id>/subsigntureb/delete/<int:id>/',subsignture_b_delete,name="subsignture_b_delete" ),
  # Result
  path('yfcase/<int:yfcase_id>/result/create/',result_create,name="result_create" ),
  path('yfcase/<int:yfcase_id>/result/update/<int:id>/',result_update,name="result_update" ),

  path('ajax/load-townships/', load_townships, name='ajax_load_townships'),
  
  # 匯出資料
  path('export-excel/',export_yfcase,name='export'),


]

templates/yfcase/partials/build.html
<!-- 建物 -->
{% load urlify %}

<style>
  .build__table { border: 3px solid black; }
  .build__th { background-color: DeepSkyBlue; border: 1px solid black; text-align: center;font-size: 1.2em;} 
  .build__td { border: 1px dotted black; font-size: 1.2em; }


  .build__th__7 { width: 7%; }
  .build__th__10 { width: 10%; }
  .build__th__15 { width: 15%; }
</style>

<table class="build__table">
  <tr>
    {% if request.user == object.user or request.user.userRole == 1 %}
      <th class="build__th build__th__10" rowspan="2">操作</th>
    {% endif %}
    <th class="build__th" rowspan="2">
      建號
    </th>
    <th class="build__th build__th__15" rowspan="2">建坪(平方公尺)</th>
    <th class="build__th build__th__10" rowspan="2">持分</th>  
    <th class="build__th" colspan="2">建坪持分(平方公尺)</th>
    <th class="build__th build__th__15" rowspan="2">
      <div style="font-size:2vmin;color: red;background-color:Cornsilk;text-align:center;">
       使用分區：{{ object.builds.first.buildUsePartition|default_if_none:"" }}
      </div>
      建物型/使用
    </th>
  </tr>
  <tr>
    <th class="build__th build__th__10">(原)</th>
    <th class="build__th build__th__10">(計算後)</th>
  </tr>
  {% for build in object.builds.all %}
    <tr>
      {% if request.user == object.user or request.user.userRole == 1 %}
        <td class="build__td">
          <a class="btn btn-success btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:build_update' object.id build.id %}" role="button">變更</a>
          <a class="btn btn-danger btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:build_delete' object.id build.id %}" role="button">刪除</a>
        </td>
      {% endif %}
      <td class="build__td text-left">
        <div style="font-size:12pt;"> 
          {% if build.buildNumber %}
            {% if build.buildUrl != None %}
              <a href="{{ build.buildUrl }}" target="_blank">
                {{ object.yfcaseBigSection }}段{{ build.buildNumber }}
              </a>
            {% else %}
              {{ object.yfcaseBigSection }}段{{ build.buildNumber }}
            {% endif %}
          {% endif %}
        </div>
      </td>

      <td class="build__td">
        {% if build.buildArea != 0 %}
          {{ build.buildArea }}
        {% endif %}
      </td>
      <td class="build__td">
        {% if build.buildHoldingPointPersonal > 0 and build.buildHoldingPointAll > 0 %}
          <div style="margin: 0px 10px;">{{ build.buildHoldingPointPersonal }}</div>
          <div style="border-top: 1px solid black;width:auto; display:inline-block !important; display:inline;padding:0px 10px;">{{ build.buildHoldingPointAll }}</div>
        {% endif %}
      </td>
      <td class="build__td">
        {% if build.buildHoldingPointPersonal > 0 and build.buildHoldingPointAll > 0 %}
          {{ build.get_build_holding_point_area|floatformat:"2" }}
        {% endif %}
      </td>
      <td class="build__td">
        {% if build.buildTypeUse == "公設" %}
          {{ build.get_build_first_not_add_and_not_public_holding_point_area|floatformat:"2" }}
        {% elif build.buildTypeUse == "增建-持分後坪數打對折" %}
          {{ build.get_after_add_holding_point_area|floatformat:"2" }}
        {% else %}
          {{ build.get_build_holding_point_area|floatformat:"2" }}
        {% endif %}
      </td>
      <td class="build__td">
        {{ build.buildTypeUse|isWordCount:9|default_if_none:"" }}
      </td>
    </tr>
  {% endfor %}
</table>

  

templates/yfcase/partials/land.html
<!-- 土地 -->
{% load urlify %}

<style>
  .land__table { border: 3px solid black;}
  .land__th { background-color: Aquamarine; border: 1px solid black; text-align: center;font-size: 1.2em;} 
  .land__td { border: 1px dotted black;font-size: 1.2em; }
  .link__button { font-size:12pt; }
  .land__th__7 { width: 7%; }
  .land__th__10 { width: 10%; }
  .land__th__15 { width: 15%; }
</style>


<table class="land__table">
  <tr>
    {% if request.user == object.user or request.user.userRole == 1 %}
      <th class="land__th land__th__10">操作</th>
    {% endif %}
    <th class="land__th">地號</th>
    <th class="land__th">地坪(平方公尺)</th>
    <th class="land__th">持分</th>
    <th class="land__th">地坪持分(平方公尺)</th>
  </tr>
  {% for land in object.lands.all %}
    <tr>
      {% if request.user == object.user or request.user.userRole == 1 %}
        <td class="land__td">
          <a class="btn btn-success btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:land_update' object.id land.id %}" role="button">變更</a>
          <a class="btn btn-danger btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:land_delete' object.id land.id %}" role="button">刪除</a>
        </td>
      {% endif %}
      <td class="land__td text-left">
        <div style="font-size:12pt;">
          {% if land.landNumber %}
            {% if land.landUrl != None %}
              <a href="{{ land.landUrl }}" target="_blank">
                {{ object.yfcaseBigSection }}段{{ land.landNumber }}
              </a>
            {% else %}
              {{ object.yfcaseBigSection }}段{{ land.landNumber }}
            {% endif %}
          {% endif %}
        </div>
      </td>
      <td class="land__td">
        {% if land.landArea != 0 %}
          {{ land.landArea }}
        {% endif %}
      </td>
      <td class="land__td">
        {% if land.landHoldingPointPersonal > 0 and land.landHoldingPointAll > 0 %}
          <div style="margin: 0px 10px;">{{ land.landHoldingPointPersonal }}</div>
          <div style="border-top: 1px solid black;width:auto; display:inline-block !important; display:inline;padding:0px 10px;">{{ land.landHoldingPointAll }}</div>
        {% endif %}
      </td>
      <td class="land__td">
        {% if land.landHoldingPointPersonal > 0 and land.landHoldingPointAll > 0 %}
          {{ land.get_land_holding_point_area|floatformat:"2" }}
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  
</table>

templates/yfcase/partials/object_building.html
<!-- 參考物件 -->
{% load humanize %}
{% load urlify %}

<style>
  .objectbuild__table { border: 3px solid black; }
  .objectbuild__th { background-color: Thistle; border: 1px solid black; text-align: center;font-size: 1.2em;} 
  .objectbuild__td { border: 1px solid black; font-size: 1.2em;}
  
  .objectbuild__th:nth-child(1) { width: 8%; }
  .objectbuild__th:nth-child(3) { width: 12%; }
  .objectbuild__th:nth-child(4) { width: 5%; }
  .objectbuild__th:nth-child(5) { width: 30%; }
  .objectbuild__th:nth-child(6) { width: 8%; }
  .objectbuild__th__plus { width: 5%;}

  .objectbuild_info th { text-align: right; }
  .objectbuild_info td { text-align: left; }
  .objectbuild__td__line_height { line-height: 14pt; }
</style>



<table class="objectbuild__table">
  {% for objectbuild in object.objectbuilds.all %}
    <tr>
      <th class="objectbuild__th">操作</th>
      <th class="objectbuild__th">參考物件訊息</th>
      <th class="objectbuild__th">勘查員A</th>
      <th class="objectbuild__th objectbuild__th__plus">加成A</th>
      <th class="objectbuild__th">加成原因A</th>
      <th class="objectbuild__th">計算</th>
    </tr>
    <tr>
      <td class="objectbuild__td" rowspan=2>
        {% if request.user == object.user or request.user.userRole == 1 %}
          <a class="btn btn-success btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:objectbuild_update' object.id objectbuild.id %}" role="button">變更</a>
          <a class="btn btn-danger btn-sm py-0 font-weight-bold link__button" href="{% url 'yfcase:objectbuild_delete' object.id objectbuild.id %}" role="button">刪除</a>
        {% endif %}
      </td>
      <td class="objectbuild__td" rowspan=5>
        <table class="objectbuild_info">
          <tr>
            <th>
              {% if objectbuild.objectBuildStatus %}
                ({{objectbuild.objectBuildStatus}})
              {% endif %}
              地址：
            </th>
            <td>{{objectbuild.objectBuildAddress}}</td>
          </tr>
          {% if objectbuild.objectBuildHouseAge %}
            <tr>
              <th>屋齡：</th>
              <td>{{objectbuild.objectBuildHouseAge}}年</td>
            </tr>
          {% endif %}
          {% if objectbuild.objectBuildFloorHeight %}
            <tr>
              <th>樓高：</th>
              <td>{{objectbuild.objectBuildFloorHeight}}</td>
            </tr>
          {% endif %}
          {% if objectbuild.objectBuildTransactionDate %}
            <tr>
              <th>成立日期：</th>
              <td>{{ objectbuild.objectBuildTransactionDate }}</td>
            </tr>
          {% endif %}
          <tr>
            <th>總價：</th>
            <td>{{ objectbuild.objectBuildTotalPrice|floatformat:0|thousandCut }}元</td>
          </tr>
          <tr>
            <th>建坪：</th>
            <td>{{ objectbuild.objectBuildBuildArea }}坪</td>
          </tr>
          {% if objectbuild.objectBuildSubBuildArea > 0 %}
            <tr>
              <th>增坪：</th>
              <td>{{ objectbuild.objectBuildSubBuildArea }}坪X0.5</td>
            </tr>
          {% endif %}
          <tr>
            <th>單價：</th>
            <td>{{ objectbuild.get_objectbuild_ping_price|floatformat:0|thousandCut }}元</td>
          </tr>
        </table>
      </td>

      <td class="objectbuild__td">
        <div>
          {% if objectbuild.objectBuildTotalPrice >= 1000000 %}
            {% if objectbuild.objectBuildScorerA == None and objectbuild.objectBuildScorerB != request.user.userFullName and objectbuild.objectBuildScorerC != request.user.userFullName %}
              <a href="{% url 'yfcase:score_a_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
              {% if objectbuild.objectBuildScorerA %}
                <a href="{% url 'yfcase:score_a_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
              {% endif %}
            {% elif objectbuild.objectBuildScorerA != None and objectbuild.objectBuildScorerA == request.user.userFullName %}
              <a href="{% url 'yfcase:score_a_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
              <a href="{% url 'yfcase:score_a_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
            {% else %}
            {% endif %}
          {% else %}
            {% if objectbuild.objectBuildScorerA == None and objectbuild.objectBuildScorerB != request.user.userFullName %}
              <a href="{% url 'yfcase:score_a_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
              {% if objectbuild.objectBuildScorerA %}
              <a href="{% url 'yfcase:score_a_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
              {% endif %}
            {% elif objectbuild.objectBuildScorerA != None and objectbuild.objectBuildScorerA == request.user.userFullName %}
              <a href="{% url 'yfcase:score_a_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
              <a href="{% url 'yfcase:score_a_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
            {% else %}
            {% endif %}
          {% endif %}
        </div>
        <div>
          {% if objectbuild.objectBuildTotalPrice >= 1000000 %}
            {% if objectbuild.objectBuildScorerA == None %}
              {% if objectbuild.objectBuildScorerB == request.user.userFullName or objectbuild.objectBuildScorerC == request.user.userFullName %}
                該員己評
              {% endif %}
            {% else %}
              {{ objectbuild.objectBuildScorerA|otherName|default_if_none:"" }}
            {% endif %}
          {% else %}
            {% if objectbuild.objectBuildScorerA == None %}
              {% if objectbuild.objectBuildScorerB == request.user.userFullName %}
                該員己評
              {% endif %}
            {% else %}
              {{ objectbuild.objectBuildScorerA|otherName|default_if_none:"" }}
            {% endif %}
          {% endif %}
        </div>
      </td>
      <td class="objectbuild__td">{% if objectbuild.objectBuildScorerA %}{{ objectbuild.get_a_plus_value|floatformat:"2" }}{% endif %}</td>
      <td class="objectbuild__td objectbuild__td__line_height text-left">
        {% isItem objectbuild.plusItemA1 objectbuild.plusValueA1 %}
        {% isItem objectbuild.plusItemA2 objectbuild.plusValueA2 %}
        {% isItem objectbuild.plusItemA3 objectbuild.plusValueA3 %}
        {% isItem objectbuild.plusItemA4 objectbuild.plusValueA4 %}
        {% isItem objectbuild.plusItemA5 objectbuild.plusValueA5 %}
        {% isItem objectbuild.plusItemOtherA objectbuild.plusValueOtherA %}
      </td>
      <td class="objectbuild__td" rowspan=5>
        {% if objectbuild.objectBuildTotalPrice >= 1000000 %}
          {{ objectbuild.get_objectbuild_ping_price_abc_calculation|floatformat:0|thousandCut }}
        {% else %}
          {{ objectbuild.get_objectbuild_ping_price_ab_calculation|floatformat:0|thousandCut }}
        {% endif %}
      </td>
    </tr>
    <tr>
      <th class="objectbuild__th">勘查員B</th>
      <th class="objectbuild__th objectbuild__th__plus">加成B</th>
      <th class="objectbuild__th">加成原因B</th>
    </tr>
    <tr>
      <th class="objectbuild__th">現勘</th>
      <td class="objectbuild__td">
        <div>
          {% if objectbuild.objectBuildTotalPrice >= 1000000 %}
            {% if objectbuild.objectBuildScorerB == None and objectbuild.objectBuildScorerA != request.user.userFullName and objectbuild.objectBuildScorerC != request.user.userFullName %}
              <a href="{% url 'yfcase:score_b_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
              {% if objectbuild.objectBuildScorerB %}
                <a href="{% url 'yfcase:score_b_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
              {% endif %}
            {% elif objectbuild.objectBuildScorerB != None and objectbuild.objectBuildScorerB == request.user.userFullName %}
              <a href="{% url 'yfcase:score_b_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
              <a href="{% url 'yfcase:score_b_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
            {% else %}
            {% endif %}
          {% else %}
            {% if objectbuild.objectBuildScorerB == None and objectbuild.objectBuildScorerA != request.user.userFullName %}
              <a href="{% url 'yfcase:score_b_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
              {% if objectbuild.objectBuildScorerB %}
                <a href="{% url 'yfcase:score_b_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
              {% endif %}
            {% elif objectbuild.objectBuildScorerB != None and objectbuild.objectBuildScorerB == request.user.userFullName %}
              <a href="{% url 'yfcase:score_b_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
              <a href="{% url 'yfcase:score_b_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
            {% else %}
            {% endif %}
          {% endif %}
        </div>
        <div>
          {% if objectbuild.objectBuildTotalPrice >= 1000000 %}
            {% if objectbuild.objectBuildScorerB == None %}
              {% if objectbuild.objectBuildScorerA == request.user.userFullName or objectbuild.objectBuildScorerC == request.user.userFullName %}
                該員己評
              {% endif %}
            {% else %}
              {{ objectbuild.objectBuildScorerB|otherName|default_if_none:"" }}
            {% endif %}
          {% else %}
            {% if objectbuild.objectBuildScorerB == None %}
              {% if objectbuild.objectBuildScorerA == request.user.userFullName %}
                該員己評
              {% endif %}
            {% else %}
              {{ objectbuild.objectBuildScorerB|otherName|default_if_none:"" }}
            {% endif %}
          {% endif %}
        </div>
      </td>
      <td class="objectbuild__td">{% if objectbuild.objectBuildScorerB %}{{ objectbuild.get_b_plus_value|floatformat:"2" }}{% endif %}      </td>
      <td class="objectbuild__td objectbuild__td__line_height text-left">
        {% isItem objectbuild.plusItemB1 objectbuild.plusValueB1 %}
        {% isItem objectbuild.plusItemB2 objectbuild.plusValueB2 %}
        {% isItem objectbuild.plusItemB3 objectbuild.plusValueB3 %}
        {% isItem objectbuild.plusItemB4 objectbuild.plusValueB4 %}
        {% isItem objectbuild.plusItemB5 objectbuild.plusValueB5 %}
        {% isItem objectbuild.plusItemOtherB objectbuild.plusValueOtherB %}
      </td>
    </tr>
    <tr>

      <td class="objectbuild__td" rowspan=2>
        {% if objectbuild.objectBuildUrl %}
          <a href="{{ objectbuild.objectBuildUrl }}" target="_blank">
            <i class="fas fa-globe-americas fa-3x"></i>
          </a>
        {% endif %}
      </td>
      {% if objectbuild.objectBuildTotalPrice >= 1000000 %}
        <th class="objectbuild__th">勘查員C</th>
        <th class="objectbuild__th objectbuild__th__plus">加成C</th>
        <th class="objectbuild__th">加成原因C</th>
      {% else %}
        <td class="objectbuild__th bg-dark"></td>
        <td class="objectbuild__th bg-dark"></td>
        <td class="objectbuild__th bg-dark"></td>
      {% endif %}
    </tr>
    <tr>
      {% if objectbuild.objectBuildTotalPrice >= 1000000 %}
        <td class="objectbuild__td">
          <div>
            {% if objectbuild.objectBuildTotalPrice >= 1000000 %}
              {% if objectbuild.objectBuildScorerC == None and objectbuild.objectBuildScorerA != request.user.userFullName and objectbuild.objectBuildScorerB != request.user.userFullName %}
                <a href="{% url 'yfcase:score_c_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
                {% if objectbuild.objectBuildScorerC %}
                  <a href="{% url 'yfcase:score_c_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
                {% endif %}
              {% elif objectbuild.objectBuildScorerC != None and objectbuild.objectBuildScorerC == request.user.userFullName %}
                <a href="{% url 'yfcase:score_c_update' object.id objectbuild.id %}" class="btn__icon__update">評分</a>
                <a href="{% url 'yfcase:score_c_delete' object.id objectbuild.id %}" class="btn__icon__delete">刪除</a>
              {% else %}
              {% endif %}
            {% endif %}
          </div>
          <div>
            {% if objectbuild.objectBuildTotalPrice >= 1000000 %}
              {% if objectbuild.objectBuildScorerC == None %}
                {% if objectbuild.objectBuildScorerA == request.user.userFullName or objectbuild.objectBuildScorerB == request.user.userFullName %}
                  該員己評
                {% endif %}
              {% else %}
                  {{ objectbuild.objectBuildScorerC|otherName|default_if_none:"" }}
              {% endif %}
            {% endif %}
          </div>
        </td>
        <td class="objectbuild__td">{% if objectbuild.objectBuildScorerC %}{{ objectbuild.get_c_plus_value|floatformat:"2" }}{% endif %}</td>
        <td class="objectbuild__td objectbuild__td__line_height text-left">
          {% isItem objectbuild.plusItemC1 objectbuild.plusValueC1 %}
          {% isItem objectbuild.plusItemC2 objectbuild.plusValueC2 %}
          {% isItem objectbuild.plusItemC3 objectbuild.plusValueC3 %}
          {% isItem objectbuild.plusItemC4 objectbuild.plusValueC4 %}
          {% isItem objectbuild.plusItemC5 objectbuild.plusValueC5 %}
          {% isItem objectbuild.plusItemOtherC objectbuild.plusValueOtherC %}
        </td>
      {% else %}
        <td class="objectbuild__td bg-dark"></td>
        <td class="objectbuild__td bg-dark"></td>
        <td class="objectbuild__td bg-dark"></td>
      {% endif %}
    </tr>
  {% endfor %}
</table>